component_depth: 4
languages:
- java
- javascript
exclude:
- /extra/.*
- /src/fitnesse/resources/codemirror/.*
- /src/fitnesse/resources/javascript/jquery.*.js
- /src/fitnesse/resources/bootstrap/js/bootstrap.js
